const drinkOptions = [
    {
        id: 'size',
        label: 'Ukuran',
        options: ['S', 'M', 'L'],
        default: 'M',
        ui: 'level',
        pricing: {
            L: 3000,
        },
    },
    {
        id: 'sweetness',
        label: 'Tingkat Gula',
        options: ['0%', '40%', '60%', '100%'],
        default: '40%',
        ui: 'level',
    },
    {
        id: 'topping',
        label: 'Pilihan Topping',
        options: ['Tanpa Topping', 'Boba', 'Krim Keju', 'Cincau'],
        default: 'Tanpa Topping',
        pricing: {
            Boba: 3000,
            'Krim Keju': 4000,
            Cincau: 3000,
        },
    },
];

const blendedOptions = [
    {
        id: 'size',
        label: 'Ukuran',
        options: ['S', 'M', 'L'],
        default: 'M',
        ui: 'level',
        pricing: {
            L: 3000,
        },
    },
    {
        id: 'ice',
        label: 'Tingkat Es',
        options: ['Sedikit', 'Normal', 'Ekstra'],
        default: 'Normal',
        ui: 'level',
    },
    {
        id: 'topping',
        label: 'Pilihan Topping',
        options: ['Tanpa Topping', 'Krim Kocok', 'Boba'],
        default: 'Tanpa Topping',
        pricing: {
            'Krim Kocok': 3000,
            Boba: 3000,
        },
    },
];

const mealOptions = [
    {
        id: 'portion',
        label: 'Porsi',
        options: ['Reguler', 'Besar'],
        default: 'Reguler',
        pricing: {
            Besar: 5000,
        },
    },
    {
        id: 'spice',
        label: 'Level Pedas',
        options: ['Ringan', 'Sedang', 'Pedas'],
        default: 'Sedang',
    },
    {
        id: 'add_on',
        label: 'Tambahan',
        options: ['Tanpa Tambahan', 'Telur', 'Keju', 'Ekstra Ayam'],
        default: 'Tanpa Tambahan',
        pricing: {
            Telur: 3000,
            Keju: 3000,
            'Ekstra Ayam': 6000,
        },
    },
];

const snackOptions = [
    {
        id: 'portion',
        label: 'Porsi',
        options: ['Sendiri', 'Berbagi'],
        default: 'Sendiri',
        pricing: {
            Berbagi: 5000,
        },
    },
    {
        id: 'sauce',
        label: 'Saus',
        options: ['BBQ', 'Keju', 'Mayo Pedas'],
        default: 'Keju',
    },
];

const dessertOptions = [
    {
        id: 'slice',
        label: 'Potongan',
        options: ['Reguler', 'Besar'],
        default: 'Reguler',
        pricing: {
            Besar: 4000,
        },
    },
    {
        id: 'extra',
        label: 'Tambahan',
        options: ['Tanpa Tambahan', 'Ekstra Berry', 'Es Krim'],
        default: 'Tanpa Tambahan',
        pricing: {
            'Ekstra Berry': 3000,
            'Es Krim': 4000,
        },
    },
];

const riceOptions = [
    {
        id: 'portion',
        label: 'Porsi',
        options: ['Reguler', 'Jumbo'],
        default: 'Reguler',
        pricing: {
            Jumbo: 6000,
        },
    },
    {
        id: 'spice',
        label: 'Level Pedas',
        options: ['Tidak Pedas', 'Sedang', 'Pedas'],
        default: 'Sedang',
        ui: 'level',
    },
    {
        id: 'add_on',
        label: 'Tambahan',
        options: ['Tanpa Tambahan', 'Telur', 'Kerupuk', 'Sambal Ekstra'],
        default: 'Tanpa Tambahan',
        pricing: {
            Telur: 3000,
            Kerupuk: 2000,
            'Sambal Ekstra': 2000,
        },
    },
];

const satayOptions = [
    {
        id: 'portion',
        label: 'Porsi',
        options: ['5 Tusuk', '10 Tusuk'],
        default: '10 Tusuk',
    },
    {
        id: 'sauce',
        label: 'Bumbu',
        options: ['Kacang', 'Kecap Pedas', 'Campur'],
        default: 'Kacang',
    },
    {
        id: 'add_on',
        label: 'Pendamping',
        options: ['Tanpa Lontong', 'Lontong', 'Nasi'],
        default: 'Tanpa Lontong',
        pricing: {
            Lontong: 3000,
            Nasi: 5000,
        },
    },
];

const soupOptions = [
    {
        id: 'portion',
        label: 'Porsi',
        options: ['Reguler', 'Jumbo'],
        default: 'Reguler',
        pricing: {
            Jumbo: 5000,
        },
    },
    {
        id: 'spice',
        label: 'Level Sambal',
        options: ['Tanpa Sambal', 'Sedang', 'Pedas'],
        default: 'Sedang',
        ui: 'level',
    },
    {
        id: 'add_on',
        label: 'Tambahan',
        options: ['Tanpa Tambahan', 'Bakso Urat', 'Pangsit', 'Sambal Ekstra'],
        default: 'Tanpa Tambahan',
        pricing: {
            'Bakso Urat': 4000,
            Pangsit: 3000,
            'Sambal Ekstra': 2000,
        },
    },
];

const gadoOptions = [
    {
        id: 'portion',
        label: 'Porsi',
        options: ['Reguler', 'Besar'],
        default: 'Reguler',
        pricing: {
            Besar: 4000,
        },
    },
    {
        id: 'sauce',
        label: 'Bumbu Kacang',
        options: ['Normal', 'Pedas', 'Ekstra'],
        default: 'Normal',
    },
    {
        id: 'add_on',
        label: 'Tambahan',
        options: ['Tanpa Tambahan', 'Telur', 'Kerupuk'],
        default: 'Tanpa Tambahan',
        pricing: {
            Telur: 3000,
            Kerupuk: 2000,
        },
    },
];

const martabakOptions = [
    {
        id: 'size',
        label: 'Ukuran',
        options: ['Reguler', 'Besar'],
        default: 'Reguler',
        pricing: {
            Besar: 7000,
        },
    },
    {
        id: 'topping',
        label: 'Topping',
        options: ['Cokelat Kacang', 'Keju Susu', 'Campur'],
        default: 'Cokelat Kacang',
        pricing: {
            'Keju Susu': 3000,
            Campur: 5000,
        },
    },
];

const dimsumOptions = [
    {
        id: 'portion',
        label: 'Porsi',
        options: ['4 Pcs', '8 Pcs'],
        default: '4 Pcs',
        pricing: {
            '8 Pcs': 8000,
        },
    },
    {
        id: 'sauce',
        label: 'Saus',
        options: ['Saus Cabai', 'Mayo Pedas', 'Saus Kacang'],
        default: 'Saus Cabai',
    },
    {
        id: 'add_on',
        label: 'Tambahan',
        options: ['Tanpa Tambahan', 'Chili Oil', 'Keju'],
        default: 'Tanpa Tambahan',
        pricing: {
            'Chili Oil': 2000,
            Keju: 3000,
        },
    },
];

const baseProducts = [
    {
        slug: 'honey-milk-tea',
        name: 'Honey Milk Tea',
        shortName: 'Honey Milk Tea',
        category: 'Minuman',
        price: 28000,
        rating: 5.0,
        prepTime: 18,
        promo: 'Beli 1 Gratis 1',
        recommended: true,
        image: '/images/menu/honey-milk-tea.png',
        tagline: 'Teh lembut dengan sentuhan madu creamy.',
        description: 'Teh susu signature dengan aroma madu lembut, teh hitam, dan boba kenyal yang cocok untuk mood manis seharian.',
        features: ['Teh hitam segar', 'Campuran susu creamy', 'Cocok dengan boba'],
        options: drinkOptions,
    },
    {
        slug: 'matcha-latte',
        name: 'Matcha Latte',
        shortName: 'Matcha Latte',
        category: 'Minuman',
        price: 30000,
        rating: 4.9,
        prepTime: 16,
        promo: 'Diskon 15%',
        recommended: true,
        image: '/images/menu/matcha-latte.png',
        tagline: 'Matcha creamy dengan manis seimbang.',
        description: 'Matcha latte creamy dengan rasa teh hijau yang bersih dan lapisan susu lembut untuk penggemar minuman earthy.',
        features: ['Matcha premium', 'Tekstur susu lembut', 'Pahit ringan'],
        options: drinkOptions,
    },
    {
        slug: 'iced-chocolate-frappe',
        name: 'Iced Chocolate Frappe',
        shortName: 'Chocolate Frappe',
        category: 'Minuman',
        price: 32000,
        rating: 4.8,
        prepTime: 15,
        promo: 'Diskon 20%',
        recommended: true,
        image: '/images/menu/iced-chocolate-frappe.png',
        tagline: 'Dingin, kental, dan ekstra cokelat.',
        description: 'Chocolate frappe dengan krim kocok dan saus cokelat pekat, cocok untuk pencinta minuman pencuci mulut yang rasanya kuat.',
        features: ['Basis cokelat pekat', 'Topping krim kocok', 'Rasa ala kafe'],
        options: blendedOptions,
    },
    {
        slug: 'strawberry-smoothie',
        name: 'Strawberry Smoothie',
        shortName: 'Strawberry Smoothie',
        category: 'Minuman',
        price: 29000,
        rating: 4.8,
        prepTime: 14,
        promo: 'Diskon 10%',
        recommended: false,
        image: '/images/menu/strawberry-smoothie.png',
        tagline: 'Smoothie stroberi manis dengan tekstur creamy.',
        description: 'Smoothie stroberi segar dengan karakter manis ringan, creamy, dan warna yang playful untuk menu favorit siang hari.',
        features: ['Rasa berry terasa', 'Tekstur creamy', 'Akhir rasa segar'],
        options: blendedOptions,
    },
    {
        slug: 'spicy-ramen',
        name: 'Spicy Ramen',
        shortName: 'Spicy Ramen',
        category: 'Makanan Berat',
        price: 48000,
        rating: 4.9,
        prepTime: 35,
        promo: 'Diskon 15%',
        recommended: true,
        image: '/images/menu/spicy-ramen.png',
        tagline: 'Kuah kaya rasa, mi kenyal, dan hangat.',
        description: 'Ramen kuah pedas gurih dengan telur setengah matang, minyak cabai, dan topping lengkap untuk makanan hangat yang memuaskan.',
        features: ['Kuah dimasak perlahan', 'Topping telur lembut', 'Rasa umami kuat'],
        options: mealOptions,
    },
    {
        slug: 'grilled-chicken-bowl',
        name: 'Grilled Chicken Bowl',
        shortName: 'Chicken Bowl',
        category: 'Makanan Berat',
        price: 45000,
        rating: 4.8,
        prepTime: 28,
        promo: 'Populer',
        recommended: true,
        image: '/images/menu/grilled-chicken-bowl.png',
        tagline: 'Ayam glaze di atas nasi hangat.',
        description: 'Rice bowl dengan ayam glazed, telur lembut, dan taburan wijen untuk makan siang yang cepat, padat, dan tetap nyaman.',
        features: ['Glaze gurih manis', 'Rice bowl hangat', 'Protein seimbang'],
        options: mealOptions,
    },
    {
        slug: 'crispy-burger',
        name: 'Crispy Burger',
        shortName: 'Crispy Burger',
        category: 'Camilan',
        price: 39000,
        rating: 4.7,
        prepTime: 20,
        promo: 'Diskon 12%',
        recommended: true,
        image: '/images/menu/crispy-burger.png',
        tagline: 'Burger ayam renyah dengan keju lumer.',
        description: 'Burger ayam renyah dengan roti lembut, selada segar, keju, dan saus gurih untuk camilan berat yang nagih.',
        features: ['Ayam crispy keemasan', 'Lapisan keju lumer', 'Roti panggang lembut'],
        options: snackOptions,
    },
    {
        slug: 'french-fries',
        name: 'French Fries',
        shortName: 'French Fries',
        category: 'Camilan',
        price: 22000,
        rating: 4.6,
        prepTime: 12,
        promo: 'Tambahan',
        recommended: false,
        image: '/images/menu/french-fries.png',
        tagline: 'Kentang goreng klasik yang renyah.',
        description: 'Kentang goreng renyah dengan pilihan saus favorit, cocok sebagai menu pendamping untuk burger atau minuman manis.',
        features: ['Luar renyah', 'Dalam lembut', 'Cocok untuk berbagi'],
        options: snackOptions,
    },
    {
        slug: 'pepperoni-pizza',
        name: 'Pepperoni Pizza',
        shortName: 'Pepperoni Pizza',
        category: 'Spesial',
        price: 89000,
        rating: 4.9,
        prepTime: 35,
        promo: 'Paket Pesta',
        recommended: true,
        image: '/images/menu/pepperoni-pizza.png',
        tagline: 'Keju lumer dan pepperoni klasik.',
        description: 'Pizza pepperoni dengan keju lumer penuh, pinggiran renyah, dan rasa klasik yang pas untuk berbagi atau malam santai.',
        features: ['Gaya panggang stone-baked', 'Pepperoni melimpah', 'Cocok untuk 2-3 orang'],
        options: [
            {
                id: 'size',
                label: 'Ukuran',
                options: ['Sedang', 'Besar'],
                default: 'Sedang',
                pricing: {
                    Besar: 12000,
                },
            },
            {
                id: 'extra',
                label: 'Tambahan',
                options: ['Tanpa Tambahan', 'Ekstra Keju', 'Ekstra Pepperoni'],
                default: 'Tanpa Tambahan',
                pricing: {
                    'Ekstra Keju': 5000,
                    'Ekstra Pepperoni': 7000,
                },
            },
        ],
    },
    {
        slug: 'berry-cheesecake',
        name: 'Berry Cheesecake',
        shortName: 'Berry Cheesecake',
        category: 'Hidangan Manis',
        price: 34000,
        rating: 4.8,
        prepTime: 10,
        promo: 'Manis Favorit',
        recommended: false,
        image: '/images/menu/berry-cheesecake.png',
        tagline: 'Hidangan manis creamy dengan topping berry.',
        description: 'Cheesecake lembut dengan topping berry dan saus glossy untuk menutup sesi makan dengan rasa manis yang elegan.',
        features: ['Keju creamy', 'Topping berry', 'Nuansa kafe'],
        options: dessertOptions,
    },
    {
        slug: 'nasi-goreng',
        name: 'Nasi Goreng Kampung',
        shortName: 'Nasi Goreng',
        category: 'Makanan Berat',
        price: 36000,
        rating: 4.9,
        prepTime: 24,
        promo: 'Favorit Lokal',
        recommended: true,
        image: '/images/menu/nasi-goreng.png',
        tagline: 'Nasi goreng gurih dengan aroma wajan khas.',
        description: 'Nasi goreng kampung dengan telur, sayuran, kerupuk, dan rasa bumbu rumahan yang hangat untuk makan siang atau malam.',
        features: ['Aroma wajan', 'Bumbu rumahan', 'Kerupuk renyah'],
        options: riceOptions,
    },
    {
        slug: 'sate-ayam',
        name: 'Sate Ayam Madura',
        shortName: 'Sate Ayam',
        category: 'Makanan Berat',
        price: 42000,
        rating: 4.9,
        prepTime: 26,
        promo: 'Bumbu Kacang',
        recommended: true,
        image: '/images/menu/sate-ayam.png',
        tagline: 'Sate ayam bakar dengan bumbu kacang legit.',
        description: 'Sate ayam empuk dengan aroma bakaran, bumbu kacang gurih manis, dan pilihan pendamping sesuai selera.',
        features: ['Ayam empuk', 'Bumbu kacang', 'Aroma bakaran'],
        options: satayOptions,
    },
    {
        slug: 'bakso-kuah',
        name: 'Bakso Kuah Komplit',
        shortName: 'Bakso Kuah',
        category: 'Bakso',
        price: 33000,
        rating: 4.8,
        prepTime: 20,
        promo: 'Kuah Hangat',
        recommended: true,
        image: '/images/menu/bakso-kuah.png',
        tagline: 'Bakso kuah gurih dengan topping bawang renyah.',
        description: 'Semangkuk bakso kuah hangat dengan mi, bakso daging, sayuran, dan sambal yang bisa diatur sesuai mood.',
        features: ['Kuah gurih', 'Bakso daging', 'Cocok saat hujan'],
        options: soupOptions,
    },
    {
        slug: 'rendang-rice',
        name: 'Nasi Rendang Padang',
        shortName: 'Nasi Rendang',
        category: 'Makanan Berat',
        price: 52000,
        rating: 5.0,
        prepTime: 32,
        promo: 'Menu Nusantara',
        recommended: true,
        image: '/images/menu/rendang-rice.png',
        tagline: 'Rendang empuk dengan nasi putih hangat.',
        description: 'Rendang sapi berbumbu pekat dengan nasi hangat dan daun singkong, cocok untuk pesanan yang mengenyangkan.',
        features: ['Bumbu pekat', 'Daging empuk', 'Nasi hangat'],
        options: riceOptions,
    },
    {
        slug: 'mie-ayam',
        name: 'Mie Ayam Bakso',
        shortName: 'Mie Ayam',
        category: 'Mie',
        price: 34000,
        rating: 4.8,
        prepTime: 22,
        promo: 'Diskon 18%',
        recommended: false,
        image: '/images/menu/mie-ayam.png',
        tagline: 'Mi kenyal dengan ayam kecap dan bakso.',
        description: 'Mie ayam klasik dengan potongan ayam berbumbu, sayur hijau, bakso, dan kuah hangat yang ringan.',
        features: ['Mi kenyal', 'Ayam kecap', 'Kuah ringan'],
        options: soupOptions,
    },
    {
        slug: 'gado-gado',
        name: 'Gado-Gado Jakarta',
        shortName: 'Gado-Gado',
        category: 'Sayur & Salad',
        price: 31000,
        rating: 4.7,
        prepTime: 18,
        promo: 'Segar Lokal',
        recommended: false,
        image: '/images/menu/gado-gado.png',
        tagline: 'Sayuran, telur, dan bumbu kacang creamy.',
        description: 'Gado-gado segar dengan sayuran rebus, telur, kerupuk, dan siraman bumbu kacang yang bisa dibuat pedas.',
        features: ['Sayuran segar', 'Bumbu kacang', 'Pilihan lebih ringan'],
        options: gadoOptions,
    },
    {
        slug: 'ayam-geprek',
        name: 'Ayam Geprek Sambal',
        shortName: 'Ayam Geprek',
        category: 'Makanan Berat',
        price: 38000,
        rating: 4.9,
        prepTime: 24,
        promo: 'Pedas Favorit',
        recommended: true,
        image: '/images/menu/ayam-geprek.png',
        tagline: 'Ayam crispy dengan sambal bawang pedas.',
        description: 'Ayam geprek renyah dengan sambal bawang segar, nasi hangat, dan pilihan level pedas sesuai selera.',
        features: ['Ayam crispy', 'Sambal bawang', 'Nasi hangat'],
        options: riceOptions,
    },
    {
        slug: 'martabak-manis',
        name: 'Martabak Manis Cokelat',
        shortName: 'Martabak Manis',
        category: 'Hidangan Manis',
        price: 44000,
        rating: 4.8,
        prepTime: 28,
        promo: 'Jajanan Malam',
        recommended: false,
        image: '/images/menu/martabak-manis.png',
        tagline: 'Martabak lembut dengan topping klasik.',
        description: 'Martabak manis tebal dengan pilihan cokelat kacang, keju susu, atau topping campur untuk disantap bersama.',
        features: ['Adonan lembut', 'Topping melimpah', 'Cocok berbagi'],
        options: martabakOptions,
    },
    {
        slug: 'dimsum-ayam',
        name: 'Dimsum Ayam Chili Oil',
        shortName: 'Dimsum Ayam',
        category: 'Dimsum',
        price: 32000,
        rating: 4.8,
        prepTime: 18,
        promo: 'Diskon 12%',
        recommended: true,
        image: '/images/menu/dimsum-ayam.png',
        tagline: 'Dimsum ayam lembut dengan saus pilihan.',
        description: 'Dimsum ayam kukus dengan tekstur lembut, isian gurih, dan pilihan saus cabai atau chili oil yang cocok untuk camilan hangat.',
        features: ['Kukus hangat', 'Isian ayam gurih', 'Saus pilihan'],
        options: dimsumOptions,
    },
];

export const products = baseProducts.map((product, index) => ({
    ...product,
    id: index + 1,
}));

export const categories = ['Semua', ...new Set(products.map((product) => product.category))];

export const recommendedProducts = products.filter((product) => product.recommended);

export const findProductBySlug = (slug) => products.find((product) => product.slug === slug);
